Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor    : Pimentel
// Descrição   : Programa calcula a área do circulo
// Autor(a)    : Vinicius Mesel
// Data atual  : 2/21/2017
Var
// Seção de Declarações das variáveis 
   raio: REAL

Inicio
   escreva("Escreva o raio que você quer calcular a área")
   leia(raio)
   escreva(raio * raio * pi)

Fimalgoritmo